apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resizer-pics-s3.fullname" . }}-secret
  labels:
    {{- include "resizer-pics-s3.labels" . | nindent 4 }}
type: Opaque
data:
  aws-access-key-id: {{ .Values.secrets.awsAccessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.secrets.awsSecretAccessKey | b64enc | quote }}
