apiVersion: v2
name: resizer-pics-s3
description: A Helm chart for Image Resizer API with S3 storage
type: application
version: 1.0.3
appVersion: "1.0.3"
keywords:
  - image
  - resizer
  - s3
  - api
home: https://github.com/vasyakrg/resizer-pics-s3
sources:
  - https://github.com/vasyakrg/resizer-pics-s3
maintainers:
  - name: Vasyakrg
    email: vasyakrg@gmail.com
